console:
  ports:
  - 80:8080/tcp
  environment:
    MEMCACHE_IP_ADDRESS: memcache.uc6.rancher.internal
    REDIS_IP_ADDRESS: redis.uc6.rancher.internal
    MONGODB_IP_ADDRESS: mongodb.uc6.rancher.internal:27017
    DATABASE_PORT: database.uc6.rancher.internal
  log_driver: ''
  tty: true
  log_opt: {}
  image: dvison/uc6-console:0.5
  stdin_open: true
memcache:
  log_driver: ''
  tty: true
  log_opt: {}
  image: dvison/uc6-memcached:0.5
  stdin_open: true
redis:
  log_driver: ''
  tty: true
  log_opt: {}
  image: dvison/uc6-redis:0.5
  stdin_open: true
mongodb:
  log_driver: ''
  tty: true
  log_opt: {}
  image: dvison/uc6-mongodb:0.5
  stdin_open: true
database:
  ports:
  - 5432:5432/tcp
  log_driver: ''
  tty: true
  log_opt: {}
  image: dvison/uc6-database:data
  stdin_open: true
